# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(964, 709)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.comboBox = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox.setGeometry(QtCore.QRect(0, 10, 71, 31))
        self.comboBox.setStyleSheet("font: 25 13pt \"PingFang SC\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.input_url = QtWidgets.QLineEdit(self.centralWidget)
        self.input_url.setEnabled(True)
        self.input_url.setGeometry(QtCore.QRect(70, 10, 891, 31))
        self.input_url.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_url.setAutoFillBackground(False)
        self.input_url.setStyleSheet("font: 13pt \"PingFang SC\";")
        self.input_url.setText("")
        self.input_url.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.input_url.setDragEnabled(False)
        self.input_url.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.input_url.setObjectName("input_url")
        self.input_arg = QtWidgets.QLineEdit(self.centralWidget)
        self.input_arg.setGeometry(QtCore.QRect(70, 50, 891, 31))
        self.input_arg.setStyleSheet("font: 13pt \"PingFang SC\";")
        self.input_arg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.input_arg.setObjectName("input_arg")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_2.setGeometry(QtCore.QRect(0, 50, 71, 31))
        self.comboBox_2.setStyleSheet("\n"
"font: 12 13pt \"PingFang SC\";")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.startx = QtWidgets.QPushButton(self.centralWidget)
        self.startx.setGeometry(QtCore.QRect(0, 90, 91, 31))
        self.startx.setStyleSheet("font: 25 13pt \"PingFang SC\";")
        self.startx.setObjectName("startx")
        self.output = QtWidgets.QTextBrowser(self.centralWidget)
        self.output.setGeometry(QtCore.QRect(0, 120, 981, 571))
        self.output.setStyleSheet("font: 13pt \"Kaiti SC\";")
        self.output.setObjectName("output")
        self.BurpSuite = QtWidgets.QPushButton(self.centralWidget)
        self.BurpSuite.setGeometry(QtCore.QRect(180, 90, 91, 31))
        self.BurpSuite.setStyleSheet("font: 25 13pt \"PingFang SC\";")
        self.BurpSuite.setObjectName("BurpSuite")
        self.startx_2 = QtWidgets.QPushButton(self.centralWidget)
        self.startx_2.setGeometry(QtCore.QRect(90, 90, 91, 31))
        self.startx_2.setStyleSheet("font: 25 13pt \"PingFang SC\";")
        self.startx_2.setObjectName("startx_2")
        self.startx_3 = QtWidgets.QPushButton(self.centralWidget)
        self.startx_3.setGeometry(QtCore.QRect(360, 90, 91, 31))
        self.startx_3.setStyleSheet("font: 25 13pt \"PingFang SC\";")
        self.startx_3.setObjectName("startx_3")
        self.startx_4 = QtWidgets.QPushButton(self.centralWidget)
        self.startx_4.setGeometry(QtCore.QRect(270, 90, 91, 31))
        self.startx_4.setStyleSheet("font: 25 13pt \"PingFang SC\";")
        self.startx_4.setObjectName("startx_4")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 964, 22))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.actionabout_me = QtWidgets.QAction(MainWindow)
        self.actionabout_me.setObjectName("actionabout_me")
        self.menu.addAction(self.actionabout_me)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.startx_3.clicked.connect(self.output.clear)
        self.startx_4.clicked.connect(self.input_arg.clear)
        self.startx_4.clicked.connect(self.input_url.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CheckXSS 跨站脚本漏洞验证工具"))
        self.comboBox.setItemText(0, _translate("MainWindow", "目标"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "参数"))
        self.startx.setText(_translate("MainWindow", "开始测试"))
        self.BurpSuite.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.BurpSuite.setText(_translate("MainWindow", "Burp Suite"))
        self.startx_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>测试目标和参数构造的原始链接</p></body></html>"))
        self.startx_2.setText(_translate("MainWindow", "构造测试"))
        self.startx_3.setText(_translate("MainWindow", "清空输出"))
        self.startx_4.setText(_translate("MainWindow", "清空输入"))
        self.menu.setTitle(_translate("MainWindow", "关于"))
        self.actionabout_me.setText(_translate("MainWindow", "about me"))

